[package]
name = "commons"
version = "0.1.0"
edition = "2021"
authors = ["Attila Szőke"]
description = "Common functions and resources for workspace members"

[dependencies]
walkdir = "2.3.2"
pathdiff = "0.2.1"